In [ ]:
# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.


In [1]:
#### 1. Import the numpy package under the name `np` (★☆☆)
import numpy as np

In [3]:
#### 2. Create a null vector of size 10 (★☆☆)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [111]:
#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
a = np.zeros(10)
a[4] = (1)
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [23]:
#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [26]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

In [29]:
#### 7. Create a 3x3 identity matrix (★☆☆)
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
#### 8. Create a 3x3x3 array with random values (★☆☆)
np.random.random([3,3,3])

array([[[0.12332987, 0.97000189, 0.66623417],
        [0.23239086, 0.99728114, 0.82171739],
        [0.91182497, 0.57851749, 0.18981033]],

       [[0.14550414, 0.32332327, 0.50021511],
        [0.93683432, 0.73578862, 0.30882448],
        [0.15847475, 0.19034913, 0.67309136]],

       [[0.11212644, 0.09695346, 0.75149319],
        [0.93607087, 0.81625849, 0.10680413],
        [0.43370476, 0.35199958, 0.09805569]]])

In [47]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
a = np.random.random((10,10))
print(a.min())
print(a.max())

0.0026801132071160305
0.9928355840639528


In [50]:
#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

np.mean(np.random.random(30))

0.4947583761208098

In [53]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [56]:
#### 12. Normalize a 5x5 random matrix (★☆☆)
x = np.random.random((5,5))
print((x - np.mean(x))/(np.std(x)))


[[ 0.91352148 -1.11624512  0.80617021 -1.73668843  1.73428707]
 [ 0.70830561 -1.13887354 -1.30916157  1.48261368 -0.87303782]
 [-0.07701465  0.46541898  1.28240792 -1.04987077  0.55452413]
 [ 0.89745805 -0.16757217  1.35591593 -1.59574789 -0.25783183]
 [-0.18609271 -0.04274094  0.25775351  0.13630685 -1.043806  ]]


In [67]:
#### 13. How to find common values between two arrays? (★☆☆)

a = np.random.random([6,5])
b = np.random.random([6,5])
np.intersect1d(a,b)

array([], dtype=float64)

In [78]:
#### 14. Create a random vector of size 10 and sort it (★★☆)
np.sort(np.random.random(10))


array([0.08103038, 0.12152153, 0.32171168, 0.50405956, 0.52885767,
       0.53327946, 0.61742557, 0.83370469, 0.89133696, 0.89695534])

In [92]:
#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
c = np.random.random(10)
c[c.argmax()] = 0
print(c)

[0.44804918 0.80374921 0.9615085  0.45232086 0.         0.57781411
 0.85407004 0.39299162 0.52063853 0.55830496]


In [107]:
#### 16. Subtract the mean of each row of a matrix (★★☆)
d = np.random.rand(5,10)
e = d-np.mean(d,axis=1,keepdims=True)
print(e)

[[ 0.25753203  0.34506171  0.35935922 -0.02207855 -0.43385557 -0.30786598
  -0.12535828  0.19259591  0.18698271 -0.4523732 ]
 [ 0.04459315 -0.30787359  0.15835661  0.29128019  0.45968517  0.34707079
  -0.27190767 -0.46109898 -0.44146633  0.18136067]
 [ 0.18373588  0.06786304  0.21467767 -0.13828279  0.37045355 -0.12929517
  -0.35980422 -0.22361507  0.21626413 -0.20199702]
 [ 0.25570673  0.05182843  0.21596984  0.00906593  0.13993403  0.06395445
  -0.60088792 -0.02885382  0.26749819 -0.37421585]
 [ 0.13104597  0.27584341 -0.23156065 -0.04088933 -0.21846394 -0.56865889
   0.23977935  0.1895699  -0.04181189  0.26514606]]


In [142]:
#### 17. How to get the n largest values of an array (★★★)
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


In [144]:
#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 

f = np.random.rand(5,3)
g = np.where(f > 4,f**2,f)
print(f)

[[0.491428   0.2430255  0.59731985]
 [0.14334539 0.57984164 0.39729789]
 [0.79811424 0.01923917 0.64743421]
 [0.50181162 0.72073523 0.88613483]
 [0.77858729 0.48351326 0.4797761 ]]
